#pragma once

#define FRAMERATE 8
#define WORLD_WIDTH 128
#define WORLD_HEIGHT 40
#define DIALOG_WIDTH 32
#define DIALOG_HEIGHT 4
#define VIEWPORT_WIDTH 32
#define VIEWPORT_HEIGHT 12
#define GETCH_TIMEOUT 100
