name: Test all

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install GCC, criterion and clang-tidy
      run: |
        sudo apt-get update \
        && sudo apt-get install -y gcc libcriterion-dev clang-tidy

    - name: Lint all
      run: ./scripts/lint-all.sh

    - name: Run tests
      run: ./scripts/test-all.sh
